# Dataset and dataloader parameters
dataset: 'nuScenes'
version: 'v1.0-trainval'
agent_setting: 'single_agent'
input_representation: 'graphs'
name: 'scout'

train_set_args: &ds_args
  split: 'train'
  t_h: 2
  t_f: 6
  map_extent: [ -50, 50, -20, 80 ]
  polyline_resolution: 1
  polyline_length: 20
  traversal_horizon: 15
  random_flips: True

val_set_args:
  <<: *ds_args
  split: 'train_val'
  random_flips: False

test_set_args:
  <<: *ds_args
  split: 'val'
  random_flips: False

batch_size: 64
num_workers: 64


# Encoder parameters
encoder_type: 'scout_encoder'
encoder_args:
  agent_feat_size: 5
  nbr_feat_size: 7 
  agent_enc_size: 32
  num_heads: 2
  lane_node_feat_size: 6
  lane_node_enc_size: 96
  lane_node_enc_depth: 3
  aggregator_enc_size: 32
  


# Aggregator parameters
aggregator_type: 'pgp'
aggregator_args:
  pre_train: True
  target_agent_enc_size: 32
  node_enc_size: 32
  pi_h1_size: 32
  pi_h2_size: 32
  horizon: 15
  num_samples: 1000
  emb_size: 128
  num_heads: 32 

# # Aggregator parameters
# aggregator_type: 'global_attention'
# aggregator_args: 
#   target_agent_enc_size: 32
#   context_enc_size: 32
#   emb_size: 128
#   num_heads: 32


# Decoder parameters
decoder_type: 'lvm'
decoder_args:
  num_samples: 1000
  op_len: 12
  hidden_size: 128
  encoding_size: 160
  agg_type: 'sample_specific'
  lv_dim: 5
  num_clusters: 10

# # Decoder parameters
# decoder_type: 'mtp'
# decoder_args: 
#   num_modes: 5
#   op_len: 12
#   use_variance: True
#   hidden_size: 128
#   encoding_size: 160
#   agg_type: 'sample_specific'
#   lv_dim: 5
#   num_clusters: 10


# Optimizer parameters
optim_args:
  lr: 0.001
  scheduler_step: 10
  scheduler_gamma: 0.5




losses: ['min_ade_k', 'mtp_loss']
loss_weights: [1, 0.5]
loss_args:
  - k: 10
  - use_variance: False
  - beta: 1
  - alpha: 1

tr_metrics: ['min_ade_k', 'miss_rate_k', 'mtp_loss']
tr_metric_args:
  - k: 10
  - k: 10
    dist_thresh: 2
  - dummy: 0
  - use_variance: False

val_metrics: ['min_ade_k','min_ade_k', 'miss_rate_k', 'miss_rate_k', 'mtp_loss']
val_metric_args:
  - k: 5
  - k: 10
  - k: 5
    dist_thresh: 2
  - k: 10
    dist_thresh: 2
  - dummy: 0
  - use_variance: False

losses: ['min_ade_k', 'pi_bc']
loss_weights: [1, 0.5]
loss_args:
  - k: 10
  - dummy: 0
  
tr_metrics: ['min_ade_k', 'miss_rate_k', 'pi_bc']
tr_metric_args:
  - k: 10
  - k: 10
    dist_thresh: 2
  - dummy: 0

val_metrics: ['min_ade_k','min_ade_k', 'miss_rate_k', 'miss_rate_k', 'pi_bc']
val_metric_args:
  - k: 5
  - k: 10
  - k: 5
    dist_thresh: 2
  - k: 10
    dist_thresh: 2
  - dummy: 0


log_freq: 100
